version: '2.1'
services:
  dhmqtt:
    container_name: dhmqtt
    image: toke/mosquitto
    networks:
      - iot
    ports:
      - "32768:1883"
      - "9001:9001"
  dhnode:
    build: .
    container_name: dhnode
    networks:
      - iot
    ports:
      - "3000:3000"
networks:
  iot:
    driver: bridge
    enable_ipv6: false